services:
  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt_broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mqtt.conf:/mosquitto/config/mosquitto.conf
    restart: always

  sender-service:
    image: nginx:alpine
    container_name: nginx-sender
    ports:
      - "8081:80"
    volumes:
      - ./:/usr/share/nginx/html:ro

  webapi:
    build: 
      context: .
      dockerfile: dockerfile.api
    container_name: web_api
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      - mqtt-broker

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    dns:
      - 8.8.8.8
    extra_hosts:
      - "api.telegram.org:149.154.166.110"
    volumes:
      - grafana-storage:/var/lib/grafana  

volumes:
  grafana-storage: